name: felem
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_screenutil: ^5.8.0
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  go_router: ^7.0.1
  image_picker: ^0.8.7+5
  intl: ^0.18.1
  json_annotation: ^4.8.1
  rxdart: ^0.27.7
  shimmer: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.3
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
